### ISSUE TITLE
[Feature request] Download and Install packages in parallel

### ISSUE THREAD

**Issue by marceloatie** [openSUSE/zypper#160] opened 2018-03-10 01:15 UTC
A new option like 'zypper up --download-in-parallel' would be great.

It will download all packages and install then in parallel

'zypper up --download-as-needed' works very close to it, but it's not in parallel.

**Comment by Tellack** [comment] 2018-03-17 10:25
Yes, I totally agree with this advice. Many packages are so small that we lose even much more time on establishing the Internet connections rather than on downloading the metadata. 

So zypper should make an option of downloading packages by multiple threads, download more than one package at the same time, like dnf does. 

This can really save users' time.

**Comment by marceloatie** [comment] 2018-03-19 20:18
i mean one thread for downloading and one thread for installing, but after that i think will be easy to implement multiple thread for downloading (in further).

**Comment by shasheene** [comment] 2019-03-15 04:04
Note: this issue is a duplicate of the older issue #104 (parallel download), and the closed issue #154 (parallel install).

**Comment by shasheene** [comment] 2019-03-15 09:06
For thoroughness, linking to a newer (though closed) issue #404, requesting a parallel install feature.

**Comment by romulasry** [comment] 2020-06-04 22:10
Update?

**Comment by bzeller** [comment] 2020-06-05 06:30
For the download part this is already tracked in #104 we are working on that, as for the install in parallel part this depends completely on support from rpm and is out of our hands. Closing this issue, please follow #104 for updates.

**Closed by bzeller** 2020-06-05 06:30 UTC
Labels: feature
