### ISSUE TITLE
Automatic retry with max retries and timeout in non-interactive mode

### ISSUE THREAD

**Issue by okurz** [openSUSE/zypper#312] opened 2019-11-20 08:23 UTC
## Motivation
copy of #177 which I see only partially fixed.
openQA test in https://openqa.opensuse.org/tests/1089036#step/test_distribution/6 fails trying to retrieve packages, probably because the repository needs a refresh. We run zypper in our openQA tests with the "--non-interactive" option which seems to not regard any retry and therefore fails immediately on occasional retrieval or network problems.

## Expected result

Would be great if the non-interactive mode would also offer automatic retries. Optionally on top: Command line options for e.g. --max-retries and --retry-wait-time (for waiting between the retries)

## Further details

Always latest result in this scenario: [latest](https://openqa.opensuse.org/tests/latest?arch=x86_64&distri=openqa&flavor=dev&machine=64bit-2G&test=openqa_install%2Bpublish&version=Tumbleweed)

**Comment by mlandres** [comment] 2019-11-20 08:44
Why should we retry on _404-file not found_? Shall we wait for it to become available on the server someday? If you repos lack a refresh, a retry won't help you.

**Comment by okurz** [comment] 2019-11-20 08:54
Yes, but am I right that there can still be a race condition with

```
zypper ref
<repo changes in the meantime>
zypper in
```

?

Of course by not refreshing zypper would not know that there is a new file. So I guess a retry would not be helpful if the option "no-refresh" is given but can we retry *with* refresh?

**Comment by mlandres** [comment] 2019-11-20 09:52
Sorry, I don't get your point. `zypper in` also refreshes (unless you disable repos `autorefresh` or pass `--no-refresh` to `in`, but then you asked for it).

But here may always be a change on the server. If the computed and confirmed transaction based on the last metadata we saw can not be committed you must redo the whole command. A metadata refresh invalidates the resolver result, conflict resolution as well as confirmed licenses etc. 

Apart of that, AFAIK our servers keep the last version of a package a while longer than the metadata. So running transactions can usually complete even if the package on the server was updated.

**Comment by okurz** [comment] 2019-11-21 05:45
hm, ok. I just know that we still have some workarounds with retry for zypper in https://github.com/os-autoinst/os-autoinst-distri-opensuse , our main openQA test distribution for openSUSE and SLE and we should rather fix problems in zypper – if there are any – rather than workaround in codes. One issue is fixed hence I proposed to remove the according workaround in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8961 . Not sure if others are real.

**Comment by mlandres** [comment] 2019-11-21 13:18
> ```
> zypper ref
> <repo changes in the meantime>
> zypper in
> ```

I don't know how much time openQA spends between `ref` and `in` that a repo change in the meantime is a frequent issue. In bugs (like `bsc#1157434`) I often see that repos have autorefresh disabled. In those cases you should not waste much time between `ref` and `in`.

**Comment by okurz** [comment] 2019-11-21 13:33
It's not that openQA spends much time between "ref" and "in" but rather that we have so many test runs :) But maybe the problem is really how you describe. We would need to check the test code and test properly. So if you think there is no room for improvement on the zypper side feel free to close this issue.

**Comment by okurz** [comment] 2019-11-22 08:44
Please take a look into https://openqa.opensuse.org/tests/1092187#step/openqa_webui/5 showing that we first add a repo with auto-refresh enabled and then https://openqa.opensuse.org/tests/1092187/file/video.ogv#t=29.29,29.83  showing the retrieval from download.opensuse.org failing. So to me it seems what I described in https://github.com/openSUSE/zypper/issues/312#issuecomment-555904850

**Comment by mlandres** [comment] 2019-11-25 10:20
@okurz Sorry, I forgot about the `repo.refresh.delay = 10` in `/etc/zypp/zypp.conf`. OpenQA systems may want to set it to a smaller value, maybe `1` or even `0`. It tells how long (minutes) to cache refreshed metadata.

**Comment by okurz** [comment] 2019-11-26 10:29
Nice hint! We could try this out but I do not understand yet why openQA should be treated any differently than what a normal user does. Can you explain why the system level tests on openQA should differ?

**Comment by mlandres** [comment] 2019-11-27 11:08
It depends on how often your unerlying OBS repo changes. If you say you often experience 404 issues because the cached metadata are outdated, you can decrease the cache time or do more explicit refreshs before the repo that change rapidly is used (zypper ref -f devel:openQA).

**Comment by okurz** [comment] 2019-11-27 21:58
So for now in https://github.com/os-autoinst/os-autoinst-distri-openQA/pull/55 we did a `zypper ref -f` before we try the installation. But my understanding is that same for openQA and users zypper could still fail to retrieve packages mid-way. I guess with a static pool repo and maintenance update channels where only new package versions are added but none removed this might be virtually impossible to hit but for every Tumbleweed user or user of OBS repos this sounds like something that can happen much more likely.

**Comment by mlandres** [comment] 2019-11-28 14:30
It can always happen if packages are removed from a repo while transactions are running. OBS could mitigate this when publishing a new repo content. Keeping the old package versions in place for e.g. another hour would allow most transactions to complete.

**Closed by mlandres** 2019-11-28 14:30 UTC

**Comment by ntlug** [comment] 2021-12-20 21:27
I get lots of errors (fairly regularly) when doing a zypper dup and trying to download the rpms.  Interactively, I have to hit 'r' to retry which usually succeeds.  There are many things that can cause a failure, from a bad mirror host, to something even local, like a network driver than isn't quite "right" yet.  The ability to keep retrying for a count with time interval between retries seems logical to me.  Would save me a great deal of time.

**Comment by bubbleguuum** [comment] 2022-05-14 16:31
Got many failure on a `zypper dup` involving download 5000 packages after the GCC 12.1 recompile, requiring to manually retry each failed download which is super tedious. We need to have this automated as suggested in this report.

**Comment by digitaltrails** [comment] 2022-09-03 08:50
It's not very convenient, but you can work around the problem by using expect:
```
#!/usr/bin/expect
set timeout -1
spawn zypper --no-color dup --auto-agree-with-licenses  --no-allow-vendor-change
expect "*Continue? * shows all options* (y): " { send -- "y\r" }
while {1 == 1} {
    expect \
        "*Abort, retry, ignore? * shows all options* (a): " { 
            sleep 30 
            send -- "r\r"
        } \
        eof { exit 0 }
}
```

**Comment by victorhck** [comment] 2022-09-03 10:55
A lot of "Curl error 16" in the current huge update in Tumbleweed... so I may say that maybe an automatic retry would be useful if you don't want to spend many time watching a screen full of text scrolling up and waiting for the next error message to press "r".
