### ISSUE TITLE
Zypper on Tumbleweed segfaults on package installs

### ISSUE THREAD

**Issue by coryan** [openSUSE/zypper#307] opened 2019-11-13 19:08 UTC
Can reliably reproduce using:

```
docker pull opensuse/tumbleweed && docker build -f Dockerfile .
```

where `Dockerfile` just contains:

```
FROM opensuse/tumbleweed:latest

RUN zypper refresh && \
    zypper install -y gcc-c++
```

**Comment by mlandres** [comment] 2019-11-14 10:27
@coryan I can't reproduce it. Can you provide the `/var/log/zypper.log` showing the crashing command. The log should contain a backtrace. That's what we'd need for now.

**Comment by coryan** [comment] 2019-11-14 13:50
Certainly.  Though this morning it crashes in the `refresh` step :confused: I am including two separate runs in case that helps.

[zypper.log-1.txt](https://github.com/openSUSE/zypper/files/3846767/zypper.log-1.txt)

[zypper.log-2.txt](https://github.com/openSUSE/zypper/files/3846765/zypper.log-2.txt)

**Comment by mlandres** [comment] 2019-11-14 14:07
Thanks. I appears to be the same issue as #305 and [bsc#1156481](https://bugzilla.opensuse.org/show_bug.cgi?id=1156481).

**Comment by mlandres** [comment] 2019-11-14 16:49
@coryan Do you happen to use curl 7.67? bsc#1156481 contains some hint  that there might be a bug in this version. So downgrading curl could be a workaround  for now.

**Comment by coryan** [comment] 2019-11-14 17:21
@mlandres a workaround would be welcome, but I need to start from a Docker image (I use this in our CI builds, and we start from a "clean" docker pull for a host of reasons).  It seems I cannot even do the downgrade: that seems to require a `zypper refresh` and zypper crashes.  Do you know if there is a previous version of the opensuse/tumbleweed Docker image I could start from?

**Comment by mlandres** [comment] 2019-11-14 18:15
@coryan Sorry, but I'm no docker user. I don't know.

**Comment by mlandres** [comment] 2019-11-15 09:44
Closing it here. Issue continues at [bsc#1156481](https://bugzilla.opensuse.org/show_bug.cgi?id=1156481)
(Curl fix is on the way to factory)

**Closed by mlandres** 2019-11-15 09:44 UTC

**Comment by coryan** [comment] 2019-11-15 16:09
Thanks for the quick turnaround.  Would you know where I can ask about when these fixes will make it to the `opensuse/tumbleweed` Docker images?

**Comment by mlandres** [comment] 2019-11-18 13:31
@coryan Sorry again. I'd ask on the [opensuse mailinglist](https://lists.opensuse.org/opensuse/). Maybe someone knows how frequently the images are rebuilt.
