### ISSUE TITLE
Zypper ignoring piped inputs.

### ISSUE THREAD

**Issue by PowerSnail** [openSUSE/zypper#560] opened 2024-07-22 21:20 UTC
It seems that zypper ignores piped stdin entirely.

For example, let's say `zypper dup` is encountering a conflict that needs a user-input for resolution,

```sh
echo 'c' | zypper dup
```

...does not do anything. Zypper still waits for the inputs from terminal. 

I'm aware that this is a contrived example, since there are more robust ways to tell zypper to cancel on conflict. But it does illustrate the problem. 

Thanks!

---

I've searched the man page and github issues tracker, and didn't find a solution or duplicate issue.

**Comment by mlandres** [comment] 2024-07-23 09:01
@PowerSnail maybe a duplicate of [bsc#1227205](https://bugzilla.suse.com/show_bug.cgi?id=1227205). If so, it should be fixed with zypper-1.14.75.

**Comment by PowerSnail** [comment] 2024-07-25 00:32
I don't think that is the case. I have `1.14.76`, and it's still not working for me.

**Comment by mlandres** [comment] 2024-07-26 06:55
You are right. I checked the code and actually this behavior is intended.

Regarding conflict resolution there is no guarantee that problems and solutions will appear in the same order in different zypper calls. So accepting piped input to resolve them could lead to unexpected results.

**Closed by mlandres** 2024-07-26 06:55 UTC

**Comment by mlandres** [comment] 2024-07-29 13:03
Yes. Zypper does a `fopen("/dev/tty", "r")` to read the prompt reply.

**Comment by PowerSnail** [comment] 2024-07-29 15:59
Thanks.
